/**
 * BoodschappenBuddy - Recepten Data
 * Lokaal opgeslagen receptenbestand — geen server nodig.
 */

const RECIPES = [
  {
    id: 1,
    naam: 'Aardappelpuree met gehaktballen',
    emoji: '🥔',
    beschrijving: 'Romige aardappelpuree met sappige gehaktballen en jus.',
    categorieen: ['vlees', 'comfort', 'klassiek'],
    bereidingstijd: 35,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'kruimige aardappelen', hoeveelheid: '1 kg', categorie: 'groenten' },
      { naam: 'gehakt (half om half)', hoeveelheid: '500 g', categorie: 'vlees' },
      { naam: 'melk', hoeveelheid: '100 ml', categorie: 'zuivel' },
      { naam: 'boter', hoeveelheid: '50 g', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'ei', hoeveelheid: '1 stuk', categorie: 'zuivel' },
      { naam: 'paneermeel', hoeveelheid: '3 el', categorie: 'droog' },
      { naam: 'zout en peper', hoeveelheid: 'naar smaak', categorie: 'kruiden' },
    ],
  },
  {
    id: 2,
    naam: 'Pasta Bolognese',
    emoji: '🍝',
    beschrijving: 'Klassieke Italiaanse pasta met rijke vleessaus.',
    categorieen: ['vlees', 'pasta', 'klassiek'],
    bereidingstijd: 40,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'spaghetti', hoeveelheid: '400 g', categorie: 'droog' },
      { naam: 'rundergehakt', hoeveelheid: '400 g', categorie: 'vlees' },
      { naam: 'gepelde tomaten (blik)', hoeveelheid: '400 g', categorie: 'conserven' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'tomatenpuree', hoeveelheid: '2 el', categorie: 'conserven' },
      { naam: 'geraspte Parmezaan', hoeveelheid: '50 g', categorie: 'zuivel' },
      { naam: 'olijfolie', hoeveelheid: '2 el', categorie: 'kruiden' },
      { naam: 'Italiaanse kruiden', hoeveelheid: '1 tl', categorie: 'kruiden' },
    ],
  },
  {
    id: 3,
    naam: 'Stamppot boerenkool',
    emoji: '🥬',
    beschrijving: 'Traditionele Nederlandse stamppot met rookworst.',
    categorieen: ['vlees', 'klassiek', 'comfort'],
    bereidingstijd: 30,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'kruimige aardappelen', hoeveelheid: '1 kg', categorie: 'groenten' },
      { naam: 'boerenkool (gesneden)', hoeveelheid: '500 g', categorie: 'groenten' },
      { naam: 'rookworst', hoeveelheid: '1 stuk', categorie: 'vlees' },
      { naam: 'melk', hoeveelheid: '100 ml', categorie: 'zuivel' },
      { naam: 'boter', hoeveelheid: '40 g', categorie: 'zuivel' },
      { naam: 'zout en peper', hoeveelheid: 'naar smaak', categorie: 'kruiden' },
    ],
  },
  {
    id: 4,
    naam: 'Erwtensoep',
    emoji: '🫘',
    beschrijving: 'Dikke, hartige erwtensoep — klassiek Nederlands wintergerecht.',
    categorieen: ['vlees', 'soep', 'klassiek'],
    bereidingstijd: 90,
    moeilijkheid: 'gemiddeld',
    personen: 6,
    ingredienten: [
      { naam: 'gedroogde spliterwten', hoeveelheid: '500 g', categorie: 'droog' },
      { naam: 'rookspek', hoeveelheid: '200 g', categorie: 'vlees' },
      { naam: 'rookworst', hoeveelheid: '1 stuk', categorie: 'vlees' },
      { naam: 'aardappelen', hoeveelheid: '300 g', categorie: 'groenten' },
      { naam: 'prei', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'selderij', hoeveelheid: '2 stengels', categorie: 'groenten' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'bouillon (varken)', hoeveelheid: '2 liter', categorie: 'conserven' },
    ],
  },
  {
    id: 5,
    naam: 'Nasi Goreng',
    emoji: '🍚',
    beschrijving: 'Pittige gebakken rijst met groenten en ei — Indonesian klassiek.',
    categorieen: ['vegetarisch', 'aziatisch', 'snel'],
    bereidingstijd: 20,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'rijst (gekookt)', hoeveelheid: '600 g', categorie: 'droog' },
      { naam: 'eieren', hoeveelheid: '4 stuks', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '3 teentjes', categorie: 'groenten' },
      { naam: 'nasi goreng kruidenpasta', hoeveelheid: '2 el', categorie: 'kruiden' },
      { naam: 'ketjap manis', hoeveelheid: '3 el', categorie: 'kruiden' },
      { naam: 'groenten (diepvries mix)', hoeveelheid: '200 g', categorie: 'groenten' },
      { naam: 'zonnebloemolie', hoeveelheid: '2 el', categorie: 'kruiden' },
    ],
  },
  {
    id: 6,
    naam: 'Kippensoep',
    emoji: '🍗',
    beschrijving: 'Voedzame zelfgemaakte kippensoep met groenten en vermicelli.',
    categorieen: ['vlees', 'soep', 'gezond'],
    bereidingstijd: 60,
    moeilijkheid: 'makkelijk',
    personen: 6,
    ingredienten: [
      { naam: 'kipfilet', hoeveelheid: '400 g', categorie: 'vlees' },
      { naam: 'kipbouillon', hoeveelheid: '1.5 liter', categorie: 'conserven' },
      { naam: 'wortelen', hoeveelheid: '3 stuks', categorie: 'groenten' },
      { naam: 'selderij', hoeveelheid: '3 stengels', categorie: 'groenten' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'prei', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'vermicelli', hoeveelheid: '100 g', categorie: 'droog' },
      { naam: 'peterselie', hoeveelheid: '1 bosje', categorie: 'kruiden' },
    ],
  },
  {
    id: 7,
    naam: 'Lasagne',
    emoji: '🫕',
    beschrijving: 'Klassieke Italiaanse lasagne met bolognese en bechamelsaus.',
    categorieen: ['vlees', 'pasta', 'comfort'],
    bereidingstijd: 75,
    moeilijkheid: 'gemiddeld',
    personen: 6,
    ingredienten: [
      { naam: 'lasagnebladen', hoeveelheid: '250 g', categorie: 'droog' },
      { naam: 'rundergehakt', hoeveelheid: '500 g', categorie: 'vlees' },
      { naam: 'gepelde tomaten (blik)', hoeveelheid: '400 g', categorie: 'conserven' },
      { naam: 'tomatenpuree', hoeveelheid: '2 el', categorie: 'conserven' },
      { naam: 'melk', hoeveelheid: '500 ml', categorie: 'zuivel' },
      { naam: 'bloem', hoeveelheid: '40 g', categorie: 'droog' },
      { naam: 'boter', hoeveelheid: '40 g', categorie: 'zuivel' },
      { naam: 'geraspte kaas', hoeveelheid: '150 g', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
    ],
  },
  {
    id: 8,
    naam: 'Vegetarische curry',
    emoji: '🍛',
    beschrijving: 'Romige kokoscurry met kikkererwten en groenten.',
    categorieen: ['vegetarisch', 'vegan', 'gezond'],
    bereidingstijd: 30,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'kikkererwten (blik)', hoeveelheid: '400 g', categorie: 'conserven' },
      { naam: 'kokosmelk', hoeveelheid: '400 ml', categorie: 'conserven' },
      { naam: 'currypasta (geel)', hoeveelheid: '2 el', categorie: 'kruiden' },
      { naam: 'bloemkool', hoeveelheid: '1 stuks', categorie: 'groenten' },
      { naam: 'spinazie', hoeveelheid: '100 g', categorie: 'groenten' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'rijst', hoeveelheid: '300 g', categorie: 'droog' },
      { naam: 'limoen', hoeveelheid: '1 stuk', categorie: 'groenten' },
    ],
  },
  {
    id: 9,
    naam: 'Zalmfilet met groenten',
    emoji: '🐟',
    beschrijving: 'Sappige zalmfilet uit de oven met seizoensgroenten.',
    categorieen: ['vis', 'gezond', 'snel'],
    bereidingstijd: 25,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'zalmfilet', hoeveelheid: '600 g', categorie: 'vlees' },
      { naam: 'courgette', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'paprika', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'kerstomaatjes', hoeveelheid: '200 g', categorie: 'groenten' },
      { naam: 'citroen', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'olijfolie', hoeveelheid: '3 el', categorie: 'kruiden' },
      { naam: 'Provençaalse kruiden', hoeveelheid: '1 tl', categorie: 'kruiden' },
    ],
  },
  {
    id: 10,
    naam: 'Pannenkoeken',
    emoji: '🥞',
    beschrijving: 'Luchtige Nederlandse pannenkoeken — groot en dun.',
    categorieen: ['vegetarisch', 'klassiek', 'comfort'],
    bereidingstijd: 30,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'bloem', hoeveelheid: '250 g', categorie: 'droog' },
      { naam: 'melk', hoeveelheid: '500 ml', categorie: 'zuivel' },
      { naam: 'eieren', hoeveelheid: '3 stuks', categorie: 'zuivel' },
      { naam: 'boter', hoeveelheid: '50 g', categorie: 'zuivel' },
      { naam: 'zout', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'stroop of jam', hoeveelheid: 'naar smaak', categorie: 'divers' },
    ],
  },
  {
    id: 11,
    naam: 'Risotto met champignons',
    emoji: '🍄',
    beschrijving: 'Romige Italiaanse risotto met verse champignons en Parmezaan.',
    categorieen: ['vegetarisch', 'comfort', 'gemiddeld'],
    bereidingstijd: 45,
    moeilijkheid: 'gemiddeld',
    personen: 4,
    ingredienten: [
      { naam: 'risottorijst', hoeveelheid: '300 g', categorie: 'droog' },
      { naam: 'champignons', hoeveelheid: '400 g', categorie: 'groenten' },
      { naam: 'groentebouillon', hoeveelheid: '1 liter', categorie: 'conserven' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'geraspte Parmezaan', hoeveelheid: '80 g', categorie: 'zuivel' },
      { naam: 'droge witte wijn', hoeveelheid: '100 ml', categorie: 'divers' },
      { naam: 'boter', hoeveelheid: '40 g', categorie: 'zuivel' },
      { naam: 'tijm', hoeveelheid: '1 tl', categorie: 'kruiden' },
    ],
  },
  {
    id: 12,
    naam: 'Kip wraps',
    emoji: '🌯',
    beschrijving: 'Makkelijke wraps gevuld met gegrilde kip en verse groenten.',
    categorieen: ['vlees', 'snel', 'gezond'],
    bereidingstijd: 20,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'tortillawraps', hoeveelheid: '8 stuks', categorie: 'brood' },
      { naam: 'kipfilet', hoeveelheid: '500 g', categorie: 'vlees' },
      { naam: 'sla (ijsbergsla)', hoeveelheid: '1/2 stuk', categorie: 'groenten' },
      { naam: 'tomaat', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'komkommer', hoeveelheid: '1/2 stuk', categorie: 'groenten' },
      { naam: 'paprika', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'zure room of crème fraîche', hoeveelheid: '100 ml', categorie: 'zuivel' },
      { naam: 'paprikapoeder', hoeveelheid: '1 tl', categorie: 'kruiden' },
    ],
  },
  {
    id: 13,
    naam: 'Omelet met groenten',
    emoji: '🍳',
    beschrijving: 'Snelle en gezonde omelet gevuld met verse groenten.',
    categorieen: ['vegetarisch', 'snel', 'gezond'],
    bereidingstijd: 15,
    moeilijkheid: 'makkelijk',
    personen: 2,
    ingredienten: [
      { naam: 'eieren', hoeveelheid: '6 stuks', categorie: 'zuivel' },
      { naam: 'paprika', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'champignons', hoeveelheid: '150 g', categorie: 'groenten' },
      { naam: 'spinazie', hoeveelheid: '50 g', categorie: 'groenten' },
      { naam: 'ui', hoeveelheid: '1/2 stuk', categorie: 'groenten' },
      { naam: 'geraspte kaas', hoeveelheid: '50 g', categorie: 'zuivel' },
      { naam: 'boter', hoeveelheid: '20 g', categorie: 'zuivel' },
      { naam: 'zout en peper', hoeveelheid: 'naar smaak', categorie: 'kruiden' },
    ],
  },
  {
    id: 14,
    naam: 'Couscous met groenten',
    emoji: '🫙',
    beschrijving: 'Snelle couscous salade met gegrilde groenten en feta.',
    categorieen: ['vegetarisch', 'gezond', 'snel'],
    bereidingstijd: 20,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'couscous', hoeveelheid: '300 g', categorie: 'droog' },
      { naam: 'courgette', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'aubergine', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'paprika', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'fetakaas', hoeveelheid: '150 g', categorie: 'zuivel' },
      { naam: 'olijfolie', hoeveelheid: '4 el', categorie: 'kruiden' },
      { naam: 'Marokkaanse kruidenmix', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'munt of peterselie', hoeveelheid: '1 bosje', categorie: 'kruiden' },
    ],
  },
  {
    id: 15,
    naam: 'Gehaktbrood',
    emoji: '🥩',
    beschrijving: 'Sappig gehaktbrood met ui en kruiden, perfect voor door de week.',
    categorieen: ['vlees', 'klassiek', 'comfort'],
    bereidingstijd: 65,
    moeilijkheid: 'makkelijk',
    personen: 6,
    ingredienten: [
      { naam: 'gehakt (half om half)', hoeveelheid: '700 g', categorie: 'vlees' },
      { naam: 'ei', hoeveelheid: '2 stuks', categorie: 'zuivel' },
      { naam: 'paneermeel', hoeveelheid: '4 el', categorie: 'droog' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'mosterd', hoeveelheid: '1 el', categorie: 'kruiden' },
      { naam: 'peterselie', hoeveelheid: '1 el', categorie: 'kruiden' },
      { naam: 'worcestershiresaus', hoeveelheid: '1 el', categorie: 'kruiden' },
    ],
  },
  {
    id: 16,
    naam: 'Tomatensoep met brood',
    emoji: '🍅',
    beschrijving: 'Huisgemaakte romige tomatensoep met knapperig brood.',
    categorieen: ['vegetarisch', 'soep', 'snel'],
    bereidingstijd: 25,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'tomaten (blik)', hoeveelheid: '800 g', categorie: 'conserven' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '2 teentjes', categorie: 'groenten' },
      { naam: 'groentebouillon', hoeveelheid: '500 ml', categorie: 'conserven' },
      { naam: 'slagroom', hoeveelheid: '100 ml', categorie: 'zuivel' },
      { naam: 'tomatenpuree', hoeveelheid: '2 el', categorie: 'conserven' },
      { naam: 'basilicum', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'stokbrood', hoeveelheid: '1 stuk', categorie: 'brood' },
    ],
  },
  {
    id: 17,
    naam: 'Bami Goreng',
    emoji: '🍜',
    beschrijving: 'Gebakken noedels met groenten en ei, Indonesische stijl.',
    categorieen: ['vegetarisch', 'aziatisch', 'snel'],
    bereidingstijd: 20,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'mie (noedels)', hoeveelheid: '400 g', categorie: 'droog' },
      { naam: 'eieren', hoeveelheid: '3 stuks', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '3 teentjes', categorie: 'groenten' },
      { naam: 'bami goreng kruidenpasta', hoeveelheid: '2 el', categorie: 'kruiden' },
      { naam: 'ketjap manis', hoeveelheid: '3 el', categorie: 'kruiden' },
      { naam: 'groenten (prei, wortel)', hoeveelheid: '300 g', categorie: 'groenten' },
      { naam: 'zonnebloemolie', hoeveelheid: '2 el', categorie: 'kruiden' },
    ],
  },
  {
    id: 18,
    naam: 'Bruine bonensoep',
    emoji: '🫘',
    beschrijving: 'Hartige bruine bonensoep met spek en groenten.',
    categorieen: ['vlees', 'soep', 'comfort'],
    bereidingstijd: 50,
    moeilijkheid: 'makkelijk',
    personen: 6,
    ingredienten: [
      { naam: 'bruine bonen (blik)', hoeveelheid: '800 g', categorie: 'conserven' },
      { naam: 'spekblokjes', hoeveelheid: '150 g', categorie: 'vlees' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'wortel', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'selderij', hoeveelheid: '2 stengels', categorie: 'groenten' },
      { naam: 'varkensbouillon', hoeveelheid: '1.5 liter', categorie: 'conserven' },
      { naam: 'thijm', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'laurierblad', hoeveelheid: '2 stuks', categorie: 'kruiden' },
    ],
  },
  {
    id: 19,
    naam: 'Caesar salade',
    emoji: '🥗',
    beschrijving: 'Frisse Caesar salade met romige dressing en croutons.',
    categorieen: ['vlees', 'salade', 'gezond'],
    bereidingstijd: 20,
    moeilijkheid: 'makkelijk',
    personen: 4,
    ingredienten: [
      { naam: 'Romeinse sla', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'kipfilet', hoeveelheid: '400 g', categorie: 'vlees' },
      { naam: 'croutons', hoeveelheid: '100 g', categorie: 'brood' },
      { naam: 'Parmezaanse kaas', hoeveelheid: '60 g', categorie: 'zuivel' },
      { naam: 'Caesar dressing', hoeveelheid: '100 ml', categorie: 'kruiden' },
      { naam: 'knoflook', hoeveelheid: '1 teentje', categorie: 'groenten' },
      { naam: 'citroen', hoeveelheid: '1/2 stuk', categorie: 'groenten' },
    ],
  },
  {
    id: 20,
    naam: 'Quiche Lorraine',
    emoji: '🥧',
    beschrijving: 'Hartige quiche met spek, kaas en romige vulling.',
    categorieen: ['vlees', 'comfort', 'klassiek'],
    bereidingstijd: 55,
    moeilijkheid: 'gemiddeld',
    personen: 6,
    ingredienten: [
      { naam: 'quichedeeg (koelvers)', hoeveelheid: '1 rol', categorie: 'divers' },
      { naam: 'spekblokjes', hoeveelheid: '200 g', categorie: 'vlees' },
      { naam: 'eieren', hoeveelheid: '4 stuks', categorie: 'zuivel' },
      { naam: 'slagroom', hoeveelheid: '200 ml', categorie: 'zuivel' },
      { naam: 'melk', hoeveelheid: '100 ml', categorie: 'zuivel' },
      { naam: 'geraspte Gruyère', hoeveelheid: '150 g', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'nootmuskaat', hoeveelheid: 'naar smaak', categorie: 'kruiden' },
    ],
  },
  {
    id: 21,
    naam: 'Linzensoep',
    emoji: '🍲',
    beschrijving: 'Voedzame linzensoep met groenten en Arabische kruiden.',
    categorieen: ['vegetarisch', 'vegan', 'soep', 'gezond'],
    bereidingstijd: 40,
    moeilijkheid: 'makkelijk',
    personen: 6,
    ingredienten: [
      { naam: 'rode linzen', hoeveelheid: '300 g', categorie: 'droog' },
      { naam: 'ui', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'knoflook', hoeveelheid: '3 teentjes', categorie: 'groenten' },
      { naam: 'wortel', hoeveelheid: '2 stuks', categorie: 'groenten' },
      { naam: 'groentebouillon', hoeveelheid: '1.5 liter', categorie: 'conserven' },
      { naam: 'komijn', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'kurkuma', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'citroen', hoeveelheid: '1 stuk', categorie: 'groenten' },
    ],
  },
  {
    id: 22,
    naam: 'Gebakken aardappelen met spiegelei',
    emoji: '🍳',
    beschrijving: 'Simpele maar heerlijke gebakken aardappelen met ei.',
    categorieen: ['vegetarisch', 'klassiek', 'snel'],
    bereidingstijd: 25,
    moeilijkheid: 'makkelijk',
    personen: 2,
    ingredienten: [
      { naam: 'vastkokende aardappelen', hoeveelheid: '600 g', categorie: 'groenten' },
      { naam: 'eieren', hoeveelheid: '4 stuks', categorie: 'zuivel' },
      { naam: 'ui', hoeveelheid: '1 stuk', categorie: 'groenten' },
      { naam: 'paprikapoeder', hoeveelheid: '1 tl', categorie: 'kruiden' },
      { naam: 'boter', hoeveelheid: '30 g', categorie: 'zuivel' },
      { naam: 'zout en peper', hoeveelheid: 'naar smaak', categorie: 'kruiden' },
    ],
  },
];

/**
 * Filter recepten op categorie
 * @param {string[]} categorieen
 * @returns {Object[]}
 */
function filterReceptenOpCategorie(categorieen) {
  if (!categorieen || categorieen.length === 0) return RECIPES;
  return RECIPES.filter(recept =>
    recept.categorieen.some(cat => categorieen.includes(cat))
  );
}

/**
 * Geef een recept terug op basis van id
 * @param {number} id
 * @returns {Object|undefined}
 */
function getReceptById(id) {
  return RECIPES.find(r => r.id === id);
}
